### ISSUE TITLE
HW-UP will brick loop chip on second run

### ISSUE THREAD

**Issue by Tail870** [sipeed/NanoKVM-UserApps#1]
Running HW-UP application twice or more will brick HDMI loopback chip rendering device unable to capture and passthrough HDMI stream.
On web GUI there's only "HDMI no signal" error.

**Comment by Tail870** [comment]
~~Somehow... I fixed it.~~

~~Not trustworthy manual:~~
~~1. Open NanoKVM Pro terminal (or connect via SSH);~~
~~2. Move to HW-UP app directory:~~
~~3. Execute: `/nanokvm_update_86102 /userapp/HW-UP/nanokvm_86102R2\[43\].bin > log.log`~~

The issue is that APP Hub contains outdated binaries. When I've downloaded FW and executable from GitHub the update procces now compleates with success status.

**Comment by Tail870** [comment]
By the way - here's output during manual updating:
```
Parsed hex value: 43
sh: line 1: echo: write error: Device or resource busy
sh: line 1: /sys/class/gpio/gpio6/direction: No such file or directory
sh: line 1: /sys/class/gpio/gpio6/value: No such file or directory
sh: line 1: /sys/class/gpio/gpio6/value: No such file or directory
sh: line 1: /sys/class/gpio/gpio6/value: No such file or directory
sh: line 1: /sys/class/gpio/gpio6/value: No such file or directory
Writing Firmware....
Waiting for chip to be ready, current code: 03
[348][03]Chip Clean Succeeded with code 00
Wrote 256 bytes to offset 0x0000 
Wrote 256 bytes to offset 0x0100 
Wrote 256 bytes to offset 0x0200 
Wrote 256 bytes to offset 0x0300 
Wrote 256 bytes to offset 0x0400 
Wrote 256 bytes to offset 0x0500 
Wrote 256 bytes to offset 0x0600 
Wrote 256 bytes to offset 0x0700 
Wrote 256 bytes to offset 0x0800 
Wrote 256 bytes to offset 0x0900 
Wrote 256 bytes to offset 0x0A00 
Wrote 256 bytes to offset 0x0B00 
Wrote 256 bytes to offset 0x0C00 
Wrote 256 bytes to offset 0x0D00 
Wrote 256 bytes to offset 0x0E00 
Wrote 256 bytes to offset 0x0F00 
Wrote 256 bytes to offset 0x1000 
Wrote 256 bytes to offset 0x1100 
Wrote 256 bytes to offset 0x1200 
Wrote 256 bytes to offset 0x1300 
Wrote 256 bytes to offset 0x1400 
Wrote 256 bytes to offset 0x1500 
Wrote 256 bytes to offset 0x1600 
Wrote 256 bytes to offset 0x1700 
Wrote 256 bytes to offset 0x1800 
Wrote 256 bytes to offset 0x1900 
Wrote 256 bytes to offset 0x1A00 
Wrote 256 bytes to offset 0x1B00 
Wrote 256 bytes to offset 0x1C00 
Wrote 256 bytes to offset 0x1D00 
Wrote 256 bytes to offset 0x1E00 
Wrote 256 bytes to offset 0x1F00 
Wrote 256 bytes to offset 0x2000 
Wrote 256 bytes to offset 0x2100 
Wrote 256 bytes to offset 0x2200 
Wrote 256 bytes to offset 0x2300 
Wrote 256 bytes to offset 0x2400 
Wrote 256 bytes to offset 0x2500 
Wrote 256 bytes to offset 0x2600 
Wrote 256 bytes to offset 0x2700 
Wrote 256 bytes to offset 0x2800 
Wrote 256 bytes to offset 0x2900 
Wrote 256 bytes to offset 0x2A00 
Wrote 256 bytes to offset 0x2B00 
Wrote 256 bytes to offset 0x2C00 
Wrote 256 bytes to offset 0x2D00 
Wrote 256 bytes to offset 0x2E00 
Wrote 256 bytes to offset 0x2F00 
Wrote 256 bytes to offset 0x3000 
Wrote 256 bytes to offset 0x3100 
Wrote 256 bytes to offset 0x3200 
Wrote 256 bytes to offset 0x3300 
Wrote 256 bytes to offset 0x3400 
Wrote 256 bytes to offset 0x3500 
Wrote 256 bytes to offset 0x3600 
Wrote 256 bytes to offset 0x3700 
Wrote 256 bytes to offset 0x3800 
Wrote 256 bytes to offset 0x3900 
Wrote 256 bytes to offset 0x3A00 
Wrote 256 bytes to offset 0x3B00 
Wrote 256 bytes to offset 0x3C00 
Wrote 256 bytes to offset 0x3D00 
Wrote 256 bytes to offset 0x3E00 
Wrote 256 bytes to offset 0x3F00 
Wrote 256 bytes to offset 0x4000 
Wrote 256 bytes to offset 0x4100 
Wrote 256 bytes to offset 0x4200 
Wrote 256 bytes to offset 0x4300 
Wrote 256 bytes to offset 0x4400 
Wrote 256 bytes to offset 0x4500 
Wrote 256 bytes to offset 0x4600 
Wrote 256 bytes to offset 0x4700 
Wrote 256 bytes to offset 0x4800 
Wrote 256 bytes to offset 0x4900 
Wrote 256 bytes to offset 0x4A00 
Wrote 256 bytes to offset 0x4B00 
Wrote 256 bytes to offset 0x4C00 
Wrote 256 bytes to offset 0x4D00 
Wrote 256 bytes to offset 0x4E00 
Wrote 256 bytes to offset 0x4F00 
Wrote 256 bytes to offset 0x5000 
Wrote 256 bytes to offset 0x5100 
Wrote 256 bytes to offset 0x5200 
Wrote 256 bytes to offset 0x5300 
Wrote 256 bytes to offset 0x5400 
Wrote 256 bytes to offset 0x5500 
Wrote 256 bytes to offset 0x5600 
Wrote 256 bytes to offset 0x5700 
Wrote 256 bytes to offset 0x5800 
Wrote 256 bytes to offset 0x5900 
Wrote 256 bytes to offset 0x5A00 
Wrote 256 bytes to offset 0x5B00 
Wrote 256 bytes to offset 0x5C00 
Wrote 256 bytes to offset 0x5D00 
Wrote 256 bytes to offset 0x5E00 
Wrote 256 bytes to offset 0x5F00 
Wrote 256 bytes to offset 0x6000 
Wrote 256 bytes to offset 0x6100 
Wrote 256 bytes to offset 0x6200 
Wrote 256 bytes to offset 0x6300 
Wrote 256 bytes to offset 0x6400 
Wrote 256 bytes to offset 0x6500 
Wrote 256 bytes to offset 0x6600 
Wrote 256 bytes to offset 0x6700 
Wrote 256 bytes to offset 0x6800 
Wrote 256 bytes to offset 0x6900 
Wrote 256 bytes to offset 0x6A00 
Wrote 256 bytes to offset 0x6B00 
Wrote 256 bytes to offset 0x6C00 
Wrote 256 bytes to offset 0x6D00 
Wrote 256 bytes to offset 0x6E00 
Wrote 256 bytes to offset 0x6F00 
Wrote 256 bytes to offset 0x7000 
Wrote 256 bytes to offset 0x7100 
Wrote 256 bytes to offset 0x7200 
Wrote 256 bytes to offset 0x7300 
Wrote 256 bytes to offset 0x7400 
Wrote 256 bytes to offset 0x7500 
Wrote 256 bytes to offset 0x7600 
Wrote 256 bytes to offset 0x7700 
Wrote 256 bytes to offset 0x7800 
Wrote 256 bytes to offset 0x7900 
Wrote 256 bytes to offset 0x7A00 
Wrote 256 bytes to offset 0x7B00 
Wrote 256 bytes to offset 0x7C00 
Wrote 256 bytes to offset 0x7D00 
Wrote 256 bytes to offset 0x7E00 
Wrote 256 bytes to offset 0x7F00 
Wrote 256 bytes to offset 0x8000 
Wrote 256 bytes to offset 0x8100 
Wrote 256 bytes to offset 0x8200 
Wrote 256 bytes to offset 0x8300 
Wrote 256 bytes to offset 0x8400 
Wrote 256 bytes to offset 0x8500 
Wrote 256 bytes to offset 0x8600 
Wrote 256 bytes to offset 0x8700 
Wrote 256 bytes to offset 0x8800 
Wrote 256 bytes to offset 0x8900 
Wrote 256 bytes to offset 0x8A00 
Wrote 256 bytes to offset 0x8B00 
Wrote 256 bytes to offset 0x8C00 
Wrote 256 bytes to offset 0x8D00 
Wrote 256 bytes to offset 0x8E00 
Wrote 256 bytes to offset 0x8F00 
Wrote 256 bytes to offset 0x9000 
Wrote 256 bytes to offset 0x9100 
Wrote 256 bytes to offset 0x9200 
Wrote 256 bytes to offset 0x9300 
Wrote 256 bytes to offset 0x9400 
Wrote 256 bytes to offset 0x9500 
Wrote 256 bytes to offset 0x9600 
Wrote 256 bytes to offset 0x9700 
Wrote 256 bytes to offset 0x9800 
Wrote 256 bytes to offset 0x9900 
Wrote 256 bytes to offset 0x9A00 
Wrote 256 bytes to offset 0x9B00 
Wrote 256 bytes to offset 0x9C00 
Wrote 256 bytes to offset 0x9D00 
Wrote 256 bytes to offset 0x9E00 
Wrote 256 bytes to offset 0x9F00 
Wrote 256 bytes to offset 0xA000 
Wrote 256 bytes to offset 0xA100 
Wrote 256 bytes to offset 0xA200 
Wrote 256 bytes to offset 0xA300 
Wrote 256 bytes to offset 0xA400 
Wrote 256 bytes to offset 0xA500 
Wrote 256 bytes to offset 0xA600 
Wrote 256 bytes to offset 0xA700 
Wrote 256 bytes to offset 0xA800 
Wrote 256 bytes to offset 0xA900 
Wrote 256 bytes to offset 0xAA00 
Wrote 256 bytes to offset 0xAB00 
Wrote 256 bytes to offset 0xAC00 
Wrote 256 bytes to offset 0xAD00 
Wrote 256 bytes to offset 0xAE00 
Wrote 256 bytes to offset 0xAF00 
Wrote 256 bytes to offset 0xB000 
Wrote 256 bytes to offset 0xB100 
Wrote 256 bytes to offset 0xB200 
Wrote 256 bytes to offset 0xB300 
Wrote 256 bytes to offset 0xB400 
Wrote 256 bytes to offset 0xB500 
Wrote 256 bytes to offset 0xB600 
Wrote 256 bytes to offset 0xB700 
Wrote 256 bytes to offset 0xB800 
Wrote 256 bytes to offset 0xB900 
Wrote 256 bytes to offset 0xBA00 
Wrote 256 bytes to offset 0xBB00 
Wrote 256 bytes to offset 0xBC00 
Wrote 256 bytes to offset 0xBD00 
Wrote 256 bytes to offset 0xBE00 
Wrote 256 bytes to offset 0xBF00 
Wrote 256 bytes to offset 0xC000 
Wrote 256 bytes to offset 0xC100 
Wrote 256 bytes to offset 0xC200 
Wrote 256 bytes to offset 0xC300 
Wrote 256 bytes to offset 0xC400 
Wrote 256 bytes to offset 0xC500 
Wrote 256 bytes to offset 0xC600 
Wrote 256 bytes to offset 0xC700 
Wrote 256 bytes to offset 0xC800 
Wrote 256 bytes to offset 0xC900 
Wrote 256 bytes to offset 0xCA00 
Wrote 256 bytes to offset 0xCB00 
Wrote 256 bytes to offset 0xCC00 
Wrote 256 bytes to offset 0xCD00 
Wrote 256 bytes to offset 0xCE00 
Wrote 256 bytes to offset 0xCF00 
Wrote 256 bytes to offset 0xD000 
Wrote 256 bytes to offset 0xD100 
Wrote 256 bytes to offset 0xD200 
Wrote 256 bytes to offset 0xD300 
Wrote 256 bytes to offset 0xD400 
Wrote 256 bytes to offset 0xD500 
Wrote 256 bytes to offset 0xD600 
Wrote 256 bytes to offset 0xD700 
Wrote 256 bytes to offset 0xD800 
Wrote 256 bytes to offset 0xD900 
Wrote 256 bytes to offset 0xDA00 
Wrote 256 bytes to offset 0xDB00 
Wrote 256 bytes to offset 0xDC00 
Wrote 256 bytes to offset 0xDD00 
Wrote 256 bytes to offset 0xDE00 
Wrote 256 bytes to offset 0xDF00 
Wrote 256 bytes to offset 0xE000 
Wrote 256 bytes to offset 0xE100 
Wrote 256 bytes to offset 0xE200 
Wrote 256 bytes to offset 0xE300 
Wrote 256 bytes to offset 0xE400 
Wrote 256 bytes to offset 0xE500 
Reached end of file before reading the specified length
Wrote last 256 bytes to offset 0xE600 
Firmware write completed
sh: line 1: /sys/class/gpio/gpio6/value: No such file or directory
sh: line 1: /sys/class/gpio/gpio6/value: No such file or directory
sh: line 1: echo: write error: Invalid argument
sh-5.1# 
```

**Comment by Tail870** [comment]
TODO:
delete HW-UP from device, download it via AppHub and run.
If success green - issue resolved; else if failed red - issue persist, need to download app from repo and sideload it via ssh for testing.

**Comment by Tail870** [comment]
Issue solved - looks like it was fixed before I've got it in a first time.

**Comment by berney** [comment]
Where to get the latest firmware. I am running NanoKVM (v1.2.14)? I ran this HW_UP app twice, and now HDMI capture is broken.

**Comment by Tail870** [comment]
@berney, delete HW_UP app from device, then reboot it and downlona&run app again. That should help you.

**Comment by berney** [comment]
> [@berney](https://github.com/berney), delete HW_UP app from device, then reboot it and downlona&run app again. That should help you.

I had deleted it and reinstalled it from the hub (but I hadn't done a reboot in between). How important is the reboot?

I noticed the `nanokvm_update_86102` script doesn't stop the `kvmcomm` service, so the `rmmod` fails and the module is still loaded, it proceeds anyway (I'm not sure if it matters, but there's error messages).

This didn't fix the issue (maybe because I never rebooted in between...?), and then I tried flashing NanoKVM Pro v1.2.14 - this caused a lot of issues as it's not a full release. I ended up bricking the device but I managed to recover it by using AXDL back to `20260119_NanoKVMPro_1_0_13.axp`. I then upgraded to v1.2.14. I have HDMI working again, but not as good.

When I first had the device, before the double HW_UP, I could do HDMI Passthrough + HDMI Capture together (both on).
After the recovery I HDMI capture wasn't working until I turned both off and then only turn HDMI Capture on. I cannot use both HDMI Capture and HDMI Passthrough simultaneously anymore.

Is there a way to check what lt6911 firmware is running, to see if I'm on the latest.

```bash
cat /proc/lt6911_info/version
```

```
NanoKVM_Pro (Desk-G) Nebm1001B
```

The firmware in the repo is 5 months old and the only commit.

```
root@kvm-a5bd 2026-04-23 1:52:33 HW-UP # fd -tf -X md5sum -b | sort
010f994581012c4e63dfdf649e7e4349 *./main.py
466c3e7e4acbf8813d62e4145defe82a *./nanokvm_update_86102
579f7705b412dbecb8f9f14a1845ad6d *./nanokvm_86102R2[43].bin
6b258978cfe4201e4fefba2c2bfb68ea *./README.md
95b81fd6e53e799917b45887521f546c *./app.toml
```

These hashes match what is in the git repo.

What is the version inside the `nanokvm_86102R2[43].bin`? is it older or newer or the same as `Nebm1001B`?

**Comment by berney** [comment]
I have bought a second NanoKVM Pro.
It came with v1.2.12 (Kernel 4.19.125, OS Ubuntu 22.04.5)

```
root@kvm-6e90:~# cat /proc/lt6911_info/version
NanoKVM_Pro (Desk-G) Nebf100A9
```

Is Nebf100A9 newer/better than Nebm1001B?
Hmm these appear to be serial numbers and not a version.

The hashes of `/userapp/HW-UP/*` matches the other device and this repo.
